### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [itzmeanjan/fCreate#1]
Hello @itzmeanjan  here is my design for fCreate!

-combination of Eye-F-C 

![fCREATE-01](https://user-images.githubusercontent.com/36028424/57910830-c111de00-78b8-11e9-9d73-16dbd2da9db3.png)

**Comment by Tobaloidee** [comment]
@itzmeanjan  what can you say?

**Comment by itzmeanjan** [comment]
Hello @Tobaloidee , 
**I'm extremely sorry to learn that, somehow I missed this issue. Thanks for your patience.**

By the way, good work, looks cool. Pretty insightful :heart: 

Please submit a PR along with app icons, so that I can merge it and rebuild app with updated icons.

Great work :+1:

**Comment by Tobaloidee** [comment]
will do @itzmeanjan  Sir! thanks!

**Comment by Tobaloidee** [comment]
Hi @itzmeanjan here's the PR #2 for the logo upload & readme update. Sorry for the delay. 😊 

You can download the different files, versions & format of the logo [HERE](https://drive.google.com/drive/u/1/folders/1HYzYPQLyegqNTzlNyNXd5JST6hsrLSSm)

Thanks so much!

**Comment by Tobaloidee** [comment]
@itzmeanjan

**Comment by itzmeanjan** [comment]
Thanks for your patience @Tobaloidee :heart: 

And great work, keep it up :+1:
